services:
  - type: web
    name: zealthy-emr
    runtime: node
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install && node seed.js
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
